Squashed commit of the following:
commit 99d5a50b33358e6d1467ad3cb4502918651972bf
Author: Jeff Henrikson <jeff@groovescale.com>
Date:   Wed Apr 24 18:14:28 2019 -0700

    config: 4000 epochs
    config: install tensorboard
    config: disable 007_evaluate
    config: 400 steps
    fix: overwrite
    improve: checkpoint_and_run.sh: detect content changes in scripts and invalidate
    fix: delete previous result so export_inference_graph.py doesn't refuse to overwrite
    config: num_steps=200
    implement: run_pipeline.sh
    refactor: break lines
    fix: paths
    config: 2 steps/epochs
    fix: paths
    fix: port to known working version of tensorflow/models
    config: known working version of tensorflow/models
    try python 3 again
    Revert "troubleshooting: try python 2"
    port: requirements
    port: call new object_detection entry point
    fix: path
    fix: paths: 007_evaluate.sh
    hack: new hard coded paths for server
    hack: old hard coded paths for server
    implement: install unzip
    implement: clone tensorflow/models locally instead of remotely
    hack: hard-coded paths
    implement: install and run protobuf
    fix: 005: PYTHONPATH
    fix: path to tensorflow/models
    fix: TypeError: iglob() got an unexpected keyword argument 'recursive'
    add: 003
    troubleshooting: try python 2

        amend

        amend: troubleshooting: try python 2

        amend: troubleshooting: try python 2

        hack: weatherballoon stdout seems slow, so pipe to null?

        amend: troubleshooting: try python 2

    config: try older version of tensorflow models, before directory move
    implement: checkpoint_and_run.sh: stop on error
    formatting
    fix: ./001_down_data.sh: line 3: unzip: command not found
    fix: PYTHONPATH
    fix: 002: PYTHONPATH
    hack: unzip outside python since inside doesn't seem to be working
    add
    add
    add
    implement: run via pip, WIP
    implement: run via conda, WIP
    implement: checkpoint_and_run.sh: named arguments for command line
    add: checkpoint_and_run.sh
    hack: paths that worked before
    config: package versions that work for me 2019-02-04